language: go

go:
  - 1.5.1

install:
  - go get launchpad.net/godeps
  - go get -d github.com/cmars/usso-login
  - $GOPATH/bin/godeps -u $GOPATH/src/github.com/cmars/usso-login/dependencies.tsv
  - go install github.com/cmars/usso-login

script: $GOPATH/bin/usso-login

